### ISSUE TITLE
DS not defined

### ISSUE THREAD

**Issue by bnomei** [bvdputte/kirby-log#2]
https://github.com/bvdputte/kirby-log/blob/master/src/Logger.php#L23

replace with `DIRECTORY_SEPARATOR`

**Comment by bvdputte** [comment]
Hmmm weird 🤔

Kirby defines this in bootstrap.php: `define('DS', '/');` ?

**Comment by bnomei** [comment]
i think its new or loadorder in composer. nevermind.
