### ISSUE TITLE
alternative

### ISSUE THREAD

**Issue by bnomei** [bvdputte/kirby-log#3]
maybe check this one out as well.

https://docs.zendframework.com/zend-log

**Comment by bvdputte** [comment]
I wanted to keep it _mean and lean_.

Is there anything lacking currently that zend-log solves?

**Comment by bnomei** [comment]
writers are way more powerful than just writing to a file. there can be multiple as well. 
like creating a custom writer that would post crtical errors to zapier triggering other stuff etc. 
plus direct browser output with firephp or chromephp instead of opening log-file in editor.

https://docs.zendframework.com/zend-log/writers/

other minor bonus stuff like processors for easier backtracing.

default would be still simple but in the right hands it would be a mighty logging tool easily installed as a plugin. 

easier for most ppl than using xdebug maybe.

**Comment by bvdputte** [comment]
I'll stick to KLogger for now, and am closing this one.
